### ISSUE TITLE
NullReferenceError on Application close

### ISSUE THREAD

**Issue by kknuut** [anakic/Jot#21]
Hi,
Thanks for great library!  I had to tinker a bit to get it working in my case, so here is the issue and solution in case it helps.  ( Great that you made it extendable!)

I have windows forms application running on,
NET 4.7.02558,
VS 2017.  
Jot  version 1.4.1.0

**ISSUE:**
When closing application, persist invokes save routine after Form has been disposed(probably?) and that results in NullReferenceError from one of custom control component Properties.

It could be that IsAlive is not working properly in this case. Offending component is toolbarDropDown inside custom control along with richtextbox. This is placed to the main Form.  Property "SelectedItem" is propagated by getter/setter on custom control level. Value of that property is readable during FormClosing and FormClosed events. CustomControl getter/setter:

` public string SelectedItem { get => (string) toolStripHeaders.SelectedItem; set =>  toolStripHeaders.SelectedItem = value;}`

**SOLUTION:**
I'm not sure if this is proper way, but my solution was to ride on FormClosing event, so I created custom ITriggerPersist class with following constructor

```
public FormPersistTrigger()
        {
            foreach (System.Windows.Forms.Form fmt in System.Windows.Forms.Application.OpenForms)
            {
                fmt.FormClosing += (s, e) => { OnApplicationClosing(); };
            }
        }
```
Current git version is using following event.
```
else //winforms
                System.Windows.Forms.Application.ApplicationExit += (s, e) => { OnApplicationClosing(); };

```

Here is the stack trace when using stock PersistTrigger:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.ToolStripComboBox.get_SelectedItem()
   at LabelWorkshop.ConfigEditorControl.get_SelectedItem() in D:\programming\LabelWorkshop\LabelWorkshop\ConfigEditorControl.cs:line 74
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Jot.TrackingConfiguration.<>c__DisplayClass65_0.<CreateDescriptor>b__0(Object obj)
   at Jot.TrackingConfiguration.Persist()
   at Jot.StateTracker.RunAutoPersist()
   at Jot.StateTracker.AutoPersistTrigger_PersistRequired(Object sender, EventArgs e)
   at Jot.Triggers.DesktopPersistTrigger.OnApplicationClosing()
   at Jot.Triggers.DesktopPersistTrigger.<.ctor>b__0_1(Object s, EventArgs e)
   at System.Windows.Forms.Application.RaiseExit()
   at System.Windows.Forms.Application.ThreadContext.Dispose(Boolean postQuit)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm
```

**Comment by anakic** [comment]
Closing old issue. I think it's not relevant since Jot v2.
